# Title of your website
title: 'CTRL-GI'

# Slogan for homepage and SEO
slogan: 'Genomics and Informatics Innovation'

# Short description for homepage & footer (max 150 chars)
description: 'Website of the CTRL-GI lab focusing on computational genomics and integrative research.'

# Footer credits (please keep credits as a thank you!)
credits: '<p>Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on the theme <a href="http://phlow.github.io/feeling-responsive/" target="_blank">Feeling Responsive</a>. Thanks to <a href="https://griffithlab.org/" target="_blank">Griffith Lab</a>.</p>'

# Main author of the website
author: CTRL-GI Team

# Base URL of the website (change to your GitHub Pages domain or custom domain)
url: 'https://ctrl-gi.github.io'
# baseurl: '/CTRL-GI'  # Uncomment and set if hosted on a subpath

# Link to GitHub edit page for content improvement
improve_content: https://github.com/ctrl-gi/ctrl-gi.github.io/edit/main/

# URL to images directory (used for easy referencing in posts/pages)
urlimg: 'https://ctrl-gi.github.io/images/'

# Site logo filename (placed in assets/images or root folder as needed)
logo: "Site_Logo4.png"

# Gems used by Jekyll for extended functionality
gems:
  - jekyll-asciidoc
  - jekyll-gist
  - jekyll-paginate

# Pagination for blog/news posts
paginate: 5
paginate_path: "news/page:num"

# Markdown processor settings
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
excerpt_separator: "<!--more-->"

# Include hidden files/folders in build
include: ['.htaccess']

# Exclude unnecessary files from production build
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - INSTALL.md
  - .gitignore
  - .DS_Store

# Site language
language: 'en'

# HTML compression settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

# Default front matter values for pages and posts
defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      show_meta: false
      comments: false
      author: CTRL-GI
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true
      comments: false
      author: CTRL-GI

# Favicons and touch icons
favicon-32x32: 'favicon-32x32.png'
touch-icon-192x192: 'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed: 'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed: 'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed: 'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed: 'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed: 'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed: 'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed: 'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed: 'apple-touch-icon-precomposed.png'
msapplication_tileimage: 'msapplication_tileimage.png'
msapplication_tilecolor: '#fabb00'

# Open Graph tags for better social sharing
og_image: 'https://ctrl-gi.github.io/images/CTRL-GI-logo.png'
og_locale: 'en_US'
og_type: 'website'

# Sass configuration
sass:
  sass_dir: _sass
  style: :compressed
  quiet_deps: true

# Google Analytics (replace with your tracking ID or remove if none)

# Asciidoctor settings
asciidoctor-enabled: false
asciidoctor:
  description: testtewtetrue
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font
